version: "3.9"
services:
  cockroachDB:
    image: cockroachdb/cockroach
    container_name: cockroachDB
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - "cockroachDB-vol:/cockroach/cockroach-data"
    command: start-single-node --insecure
  elasticsearch:
  # elasticsearch parameters https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - CLI_JAVA_OPTS="-Xms1g -Xmx1g" # Set max and min memory to 2GB
      #- node.processors=1
      #- ELASTIC_PASSWORD=Temp123!
    deploy:
      resources:
        limits:
          # cpus: "1"
          memory: 2G
volumes:
  cockroachDB-vol:
networks:
  default:
    name: Link-R-Us
